$font = Monospace

# GENERAL
general {
    hide_cursor = true
    immediate_render = true
}

animations {
    enabled = false
}

# BACKGROUND
background {
    monitor =
    color = rgb(0, 0, 0)
    blur_passes = 0
}

# Authenticate box
shape {
    monitor =
    size = 500, 100
    color =rgba(0, 0, 0, 0)
    rounding = 0
    border_size = 2
    border_color = rgba(255, 255, 255, 1)
    rotate = 0
    position = 32, -32
    halign = left
    valign = top
}

# USER
label {
    monitor =
    text = <b> @$USER </b>
    color = rgba(216, 222, 233, 0.80)
    font_size = 11
    position = 48 , -54
    halign = left
    valign = top
    zindex = 1
}

# USER
label {
    monitor =
    text = <b> password: </b>
    color = rgba(216, 222, 233, 0.80)
    font_size = 11
    position = 48, -78
    halign = left
    valign = top
    zindex = 5
}

# INPUT FIELD
input-field {
    monitor =
    size = 200, 50
    font_size = 10
    outline_thickness = -1
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = false
    outer_color = rgba(0, 0, 0, 0)
    inner_color =rgba(0, 0, 0, 0)
    font_color = rgb(255, 255, 255)
    fade_on_empty = false
    placeholder_text =
    hide_input = false
    position = 110 , -64
    halign = left
    valign = top
}

# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d - %I:%M" | tr '[:upper:]' '[:lower:]')"
    color = rgb(255, 255, 255)
    font_size = 15
    position = -32, 16
    halign = right
    valign = bottom
}
