#! /bin/sh
~/.screenlayout/home.sh

## bspwm rules
pgrep -x sxhkd > /dev/null || sxhkd &

# super hacky way to figure out the monitor setup
monitor_count=$(xrandr --listmonitors | grep -oP 'Monitors: \K\d+')

if [ "$monitor_count" -eq 1 ]; then
    bspc monitor -d I II III IV V
else
    bspc monitor HDMI-1-2 -d I II III IV V
    bspc monitor eDP-1-1 -d V VI VII
fi

# bspwm config
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config pointer_motion_interval 5

bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Screenkey manage=off

xsetroot -cursor_name left_ptr &

## launch core programs
# keybindings daemon
sxhkd &

# pape [if not managed by feh, pywal.]
nitrogen --restore &

# notification
dunst &

# top bar
wal -R
~/.config/polybar/start.sh &

# autostart programs
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dex -a &

# colors
. "${HOME}/.cache/wal/colors.sh"

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
