#! /bin/sh

## bspwm rules
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config pointer_motion_interval 16

xsetroot -cursor_name left_ptr &

## launch core programs
# keybindings daemon
sxhkd &

# picom [fancy stuff, optional]
# picom --config $HOME/.config/picom/picom.conf &

# pape [if not managed by feh, pywal.]
nitrogen --restore &

# notification
dunst &

# top bar
wal -R
polybar &

# autostart programs
dex -a &

# colors
. "${HOME}/.cache/wal/colors.sh"

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
